### PR TITLE
Working with latest Meteor version, thanks to JS and CSS bundling

### PR DESCRIPTION
**Pull request by luisivan**
Hey there,

meteor-build-client never worked for me and I guess it's because Meteor changed their building strategy. I had multiple CSS files outputted and all the JS packages were not bundled, so I added a new step that does all of that.

Thanks!
Luis

### CODE REVIEW

**Comment by frozeman** [comment]
Thanks!,

Tho i dont really understand the problem, as it works for us on all latest versions.
I will first have to take a look at our builds before i will merge that, but thanks in advance already!

**Comment by luisivan** [comment]
@frozeman got it. I was fixing #44, which was happening to us since the first day we tried it out. In a nutshell, the bug it's that just an app.js was created but no bundle with app.js + all the dependencies. Seems like it is a meteor build issue, but no idea if they did it on purpose or not.

**Comment by frozeman** [comment]
It might be the case when the `<head>` or `<body>` is missing, or there is no css file in the repo, when i remember right.

**Comment by luisivan** [comment]
@frozeman we do have both head and body, and there's a CSS file. Well, if it's working for you with the latest Meteor version, then don't worry about it!

**Comment by frozeman** [comment]
Please keep this open, should i run into problems or more people we can come back to this.

**Comment by luisivan** [comment]
Sure thing! 👍👍

**Pull request closed without merging**
