### PR TITLE
Meteor 1.3 fix for nodeEnv

### PR DESCRIPTION
**Pull request by pbastowski**
Here is the PR, as requested in issue https://github.com/frozeman/meteor-build-client/issues/25

Thanks.

### CODE REVIEW

**Comment by frozeman** [comment]
Did you test and does it fix it?

**Comment by pbastowski** [comment]
Yes and yes :)

On 15 Apr 2016, at 12:49, Fabian Vogelsteller <notifications@github.com> wrote:

Did you test and does it fix it?

**Comment by mrzafod** [comment]
Wow, @frozeman it was fast!

**Comment by pbastowski** [comment]
Did you push to npm?

I did `npm i -g meteor-build-client`, but got the old version still.

**Comment by frozeman** [comment]
I merged while being in a plane. I did publish just now.

**Comment by pbastowski** [comment]
Ahhh, high flier :) Thanks.

**Comment by mrzafod** [comment]
Thanks

**Pull request merged**
